# pyup configuration file downloaded from https://pyup.io/docs/bot/config/
# IMPORTANT All statements starting with ### are commented out params which can be uncomment

# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# configure dependency pinning globally
# default: True
# allowed: True, False
pin: True

# set the default branch
# default: empty, the default branch on GitHub
### branch: dev

# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule: "every month"

# search for requirement files
# default: True
# allowed: True, False
search: True

# Specify requirement files by hand, default is empty
# default: empty
# allowed: list
requirements:
  - requirements.txt:
      # don't update dependencies, use global 'pin' default
      update: all

# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
### label_prs: update

# assign users to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
### assignees:
###  - SamSamhuns

# configure the branch prefix the bot is using
# default: pyup-
branch_prefix: pyup/

# set a global prefix for PRs
# default: empty
### pr_prefix: "Bug #12345"

# allow to close stale PRs
# default: True
close_prs: True
